### ISSUE TITLE
Error In Install

### ISSUE THREAD

**Issue by AhrimanSefid** [XIMDEX/ximdex#107]
( ! ) Fatal error: Call to undefined function posix_getgroups() in C:\wamp\www\xi\inc\install\managers\InstallManager.class.php on line 383
Call Stack
#	Time	Memory	Function	Location
1	0.0029	163680	{main}( )	..\index.php:0
2	2.0865	9045600	InstallController->dispatch( )	..\index.php:126
3	2.0866	9045728	InstallController->compose( )	..\InstallController.class.php:72
4	2.0866	9045776	InstallStepFactory::getStep( )	..\InstallController.class.php:99
5	2.0901	9059536	Ximdex\Utils\Factory->instantiate( )	..\InstallStepFactory.class.php:74
6	2.1591	9207856	GenericInstallStep->__construct( )	..\Factory.php:85
7	2.1688	9210992	GenericInstallStep->checkPermissions( )	..\GenericInstallStep.class.php:44
8	2.1688	9211040	InstallManager->checkFilePermissions( )	..\GenericInstallStep.class.php:117
9	2.1722	9212104	InstallManager->checkGroup( )	..\InstallManager.class.php:339

**Comment by fjcarreterox** [comment]
Hi! Thanks for giving an opportunity to Ximdex CMS! 

Sadly, Ximdex CMS only runs on unix-like servers, not in Windows-based servers. 

Maybe, you can try to install VirtualBox[1] on your Windows computer and install a Debian distro[2] or similiar to install Ximdex CMS on it.

Ask us for any help you may need!

Cheers!
[1] https://www.virtualbox.org/wiki/Downloads
[2] http://virtualboxes.org/images/debian/

**Comment by AhrimanSefid** [comment]
sorry my server windows 2012 R2 Cp Plesk.
