### ISSUE TITLE
you have twelve parameters exists xss Vulnerability in search page.

### ISSUE THREAD

**Issue by helloheary** [XIMDEX/ximdex#147]
Vulnerability url :
http://demo.ximdex.com/xfind/search
Vulnerability parameters:
filter[0][value]；filter[1][value]；filter[2][value]；filter[3][value]；filter[4][value]；filter[5][value]；filter[6][value]；filter[7][value]；filter[8][value]；filter[9][value]；filter[10][value]；filter[11][value]；filter[12][value]；
payload:
javascript:alert(3294) 
Vulnerability verification:
1, open the problematic page
![image](https://user-images.githubusercontent.com/39911486/41028876-edfb1a2e-69ac-11e8-8982-a3cd6d5d2f67.png)
2, use hackbar to simulate post submission, submit payload
3, the response page will pop up the set contents according to the inserted js code
4, using another question parameters found to produce the same effect.
![image](https://user-images.githubusercontent.com/39911486/41028858-e2c659c0-69ac-11e8-9d66-b7fdefd1de3a.png)
![image](https://user-images.githubusercontent.com/39911486/41028866-e839bd5c-69ac-11e8-891f-db24fba63b09.png)

**Comment by juanpri** [comment]
This issue is not related to this repository. We acknowledge the issue and propagate to the team in charge of it.
