### ISSUE TITLE
XSS in parameter content 

### ISSUE THREAD

**Issue by whiteHat001** [XIMDEX/ximdex#148]
vulnerability url:
http://demo.ximdex.com/xowl/request.php
parameter content 
payload:
`<script>alert(document.domain)</script>`

![6 50 116ch kepit8 iu](https://user-images.githubusercontent.com/18191034/41266814-45a83018-6e2b-11e8-86d8-4a081a1dfb95.png)
Author: zhihua.yao@dbappsecurity.com.cn

**Comment by juanpri** [comment]
This issue is not related to this repository. We acknowledge the issue and propagate to the team in charge of it.
