### ISSUE TITLE
xss vulnerability in two parameters  in DMS Demo

### ISSUE THREAD

**Issue by whiteHat001** [XIMDEX/ximdex#149]
vulnerability url:
http://s03.damasco.ximdex.net/d3910b149e2ce84414e3ac292701ca52/edit
 two parameters:
Ciudad
`<img src=# onerror=alert(1)>`
Nombre
`<img src=# onerror=alert(1)>`

result:
![k6eb5atod 4h sk 4ksdo3j](https://user-images.githubusercontent.com/18191034/41267956-6dcf7ca4-6e30-11e8-9ddd-f505629aafa6.png)

Author: zhihua.yao@dbappsecurity.com.cn

**Comment by juanpri** [comment]
This issue is not related to this repository. We acknowledge the issue and propagate to the team in charge of it.

**Comment by juanpri** [comment]
This issue is not related to this repository. We acknowledge the issue and propagate to the team in charge of it.

**Comment by juanpri** [comment]
This issue is not related to this repository. We acknowledge the issue and propagate to the team in charge of it.
